# Generated by Django 6.0.3 on 2026-04-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="birth_year",
        ),
        migrations.RemoveField(
            model_name="author",
            name="nationality",
        ),
    ]
