# Generated by Django 6.0.3 on 2026-05-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_remove_author_birth_year_remove_author_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="reading",
            name="status",
            field=models.CharField(
                choices=[
                    ("reading", "Currently Reading"),
                    ("completed", "Completed"),
                    ("dropped", "Dropped"),
                ],
                db_index=True,
                default="reading",
                max_length=20,
            ),
        ),
    ]
